"""Shared verifier gate used by both solver_distill and synth_generate.

Takes a set of candidate rows (already generated by some upstream —
solver, teacher LLM, ...) and filters by:

  1. Answer correctness: ``verifier.check(pred, gt)`` per category.
  2. Optional ``[verify]: PASS`` presence (if recipe.filters.require_verify_pass).
  3. Optional CoT token cap (if recipe.filters.max_cot_tokens).

Category-less rows (``category=''``) are kept unchanged — they are
assumed to be benchmark-specific artifacts that the gate shouldn't
touch (e.g. a benchmark that hasn't adopted solvers yet).

The gate records *why* each row was dropped in the returned stats dict
so drivers can attribute losses per category / reason without re-deriving.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Callable, Iterable

from .base import GeneratedRow, Verifier
from .cot_template import has_verify_pass
from .recipe import RecipeFilters


@dataclass
class GateStats:
    kept: int = 0
    dropped_no_verifier: int = 0
    dropped_wrong_answer: int = 0
    dropped_missing_verify_mark: int = 0
    dropped_cot_too_long: int = 0
    per_category_kept: Counter = None       # type: ignore[assignment]
    per_category_dropped: Counter = None    # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.per_category_kept is None:
            self.per_category_kept = Counter()
        if self.per_category_dropped is None:
            self.per_category_dropped = Counter()

    def to_dict(self) -> dict:
        return {
            "kept": self.kept,
            "dropped_no_verifier": self.dropped_no_verifier,
            "dropped_wrong_answer": self.dropped_wrong_answer,
            "dropped_missing_verify_mark": self.dropped_missing_verify_mark,
            "dropped_cot_too_long": self.dropped_cot_too_long,
            "per_category_kept": dict(self.per_category_kept),
            "per_category_dropped": dict(self.per_category_dropped),
        }


def _default_token_counter(text: str) -> int:
    """Cheap whitespace-token cap. Callers with access to a tokenizer
    can pass in a real one via ``token_counter=`` — the default
    deliberately over-estimates so it's safe as a guardrail."""
    return len(text.split())


def apply_verifier_gate(
    rows: Iterable[GeneratedRow],
    verifiers: dict[str, Verifier],
    filters: RecipeFilters,
    *,
    token_counter: Callable[[str], int] = _default_token_counter,
) -> tuple[list[GeneratedRow], GateStats]:
    """Return (kept_rows, stats)."""
    stats = GateStats()
    kept: list[GeneratedRow] = []

    for row in rows:
        v = verifiers.get(row.category)
        # Answer correctness. Rows must carry the ground truth — they do,
        # by contract: GeneratedRow.answer IS the gt (the solver / teacher
        # copied it from the training row). Verifier checks whether the
        # CoT's boxed answer matches it.
        from .cot_template import extract_boxed
        pred = extract_boxed(row.cot)
        if v is None:
            # No verifier for this category — accept on structural grounds
            # (the row's .answer was set by the generator; if the generator
            # was solver+verifier internally, this is already correct).
            stats.dropped_no_verifier += 0   # noqa: SIM114 — explicit
        elif pred is None or not v.check(pred, row.answer):
            stats.dropped_wrong_answer += 1
            stats.per_category_dropped[row.category] += 1
            continue

        if filters.require_verify_pass and not has_verify_pass(row.cot):
            stats.dropped_missing_verify_mark += 1
            stats.per_category_dropped[row.category] += 1
            continue

        if filters.max_cot_tokens is not None:
            if token_counter(row.cot) > filters.max_cot_tokens:
                stats.dropped_cot_too_long += 1
                stats.per_category_dropped[row.category] += 1
                continue

        kept.append(row)
        stats.kept += 1
        stats.per_category_kept[row.category] += 1

    return kept, stats


__all__ = ["GateStats", "apply_verifier_gate"]
