apiVersion: v1
kind: Pod
metadata:
  name: luhanqin-moe-phase2
  namespace: default
  labels:
    app: luhanqin-moe-phase2
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: "c5.24xlarge"
  restartPolicy: Never
  containers:
  - name: workspace
    image: 801953956576.dkr.ecr.ap-south-1.amazonaws.com/ads-foundation-model-training/verl-multiturn:1.0.2
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "32"
        memory: "140Gi"
      limits:
        cpu: "64"
        memory: "170Gi"
    volumeMounts:
    - mountPath: /fsx
      name: fsx-vol
  volumes:
  - name: fsx-vol
    persistentVolumeClaim:
      claimName: fsx
