apiVersion: v1
kind: Pod
metadata:
  name: luhanqin-moe-phase1
  namespace: default
  labels:
    app: luhanqin-moe-phase1
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: "c5.24xlarge"
  restartPolicy: Never
  containers:
  - name: workspace
    image: 801953956576.dkr.ecr.ap-south-1.amazonaws.com/faim-rl-slime:base
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "16"
        memory: "64Gi"
      limits:
        cpu: "48"
        memory: "128Gi"
    volumeMounts:
    - mountPath: /fsx
      name: fsx-vol
  volumes:
  - name: fsx-vol
    persistentVolumeClaim:
      claimName: fsx
