"""Multi-framework support for training backends.

Supports generating training configurations for multiple open-source
LLM training frameworks, allowing users to choose their preferred stack.
"""

from __future__ import annotations

import enum
from dataclasses import dataclass
from typing import Dict

from autopilot.experiment.config_builder import GeneratedConfig
from autopilot.utils.logging import get_logger

log = get_logger("integrations.frameworks")


class Framework(enum.Enum):
    OLMO_CORE = "olmo_core"
    NANOTRON = "nanotron"
    LLM_FOUNDRY = "llm_foundry"
    TORCHTITAN = "torchtitan"
    MEGATRON = "megatron"


@dataclass
class FrameworkInfo:
    name: str
    description: str
    repo_url: str
    supports_pretrain: bool = True
    supports_sft: bool = True
    supports_rlhf: bool = False
    max_tested_params: float = 0  # largest model successfully trained


FRAMEWORK_REGISTRY: Dict[Framework, FrameworkInfo] = {
    Framework.OLMO_CORE: FrameworkInfo(
        name="OLMo-core",
        description="AI2's modular LLM training library (OLMo series)",
        repo_url="https://github.com/allenai/OLMo-core",
        supports_pretrain=True,
        supports_sft=True,
        supports_rlhf=False,
        max_tested_params=32e9,
    ),
    Framework.NANOTRON: FrameworkInfo(
        name="Nanotron",
        description="HuggingFace's LLM pre-training library with 3D parallelism",
        repo_url="https://github.com/huggingface/nanotron",
        supports_pretrain=True,
        supports_sft=False,
        supports_rlhf=False,
        max_tested_params=70e9,
    ),
    Framework.LLM_FOUNDRY: FrameworkInfo(
        name="LLM Foundry",
        description="Databricks/MosaicML end-to-end LLM training toolbox",
        repo_url="https://github.com/mosaicml/llm-foundry",
        supports_pretrain=True,
        supports_sft=True,
        supports_rlhf=False,
        max_tested_params=70e9,
    ),
    Framework.TORCHTITAN: FrameworkInfo(
        name="TorchTitan",
        description="PyTorch native large-scale LLM training (Meta)",
        repo_url="https://github.com/pytorch/torchtitan",
        supports_pretrain=True,
        supports_sft=False,
        supports_rlhf=False,
        max_tested_params=405e9,
    ),
    Framework.MEGATRON: FrameworkInfo(
        name="Megatron-LM",
        description="NVIDIA's large-scale transformer training framework",
        repo_url="https://github.com/NVIDIA/Megatron-LM",
        supports_pretrain=True,
        supports_sft=True,
        supports_rlhf=False,
        max_tested_params=1e12,
    ),
}


class FrameworkAdapter:
    """Adapts AutoPilot configs to different training framework formats."""

    def __init__(self, framework: Framework):
        self._framework = framework
        self._info = FRAMEWORK_REGISTRY[framework]

    @property
    def info(self) -> FrameworkInfo:
        return self._info

    def generate_config(self, config: GeneratedConfig) -> str:
        """Generate framework-specific training configuration."""
        if self._framework == Framework.OLMO_CORE:
            return self._generate_olmo_core(config)
        elif self._framework == Framework.NANOTRON:
            return self._generate_nanotron(config)
        elif self._framework == Framework.LLM_FOUNDRY:
            return self._generate_llm_foundry(config)
        elif self._framework == Framework.TORCHTITAN:
            return self._generate_torchtitan(config)
        elif self._framework == Framework.MEGATRON:
            return self._generate_megatron(config)
        raise ValueError(f"Unsupported framework: {self._framework}")

    def _generate_olmo_core(self, config: GeneratedConfig) -> str:
        from autopilot.integrations.olmo_core_bridge import OLMoCoreConfigGenerator
        return OLMoCoreConfigGenerator().generate_training_script(config)

    def _generate_nanotron(self, config: GeneratedConfig) -> str:
        model = config.model_config
        optim = config.optimizer_config
        scheduler = config.scheduler_config
        trainer = config.trainer_config
        launch = config.launch_config

        return f"""# Nanotron training config (YAML format)
# Generated by AutoPilot for: {config.name}

checkpoints:
  checkpoint_interval: {trainer.get('checkpoint_interval', 1000)}
  checkpoints_path: checkpoints/{config.name}

general:
  project: autopilot
  run: {config.name}
  seed: 42

logging:
  iteration_step_info_interval: {trainer.get('log_interval', 10)}

model:
  model_config:
    hidden_size: {model['hidden_size']}
    num_attention_heads: {model['num_heads']}
    num_hidden_layers: {model['num_layers']}
    intermediate_size: {model.get('intermediate_size', model['hidden_size'] * 4)}
    vocab_size: {model.get('vocab_size', 50304)}
    max_position_embeddings: {model.get('max_sequence_length', 4096)}
    rms_norm_eps: 1.0e-5
    rope_theta: 500000.0

optimizer:
  learning_rate: {optim['lr']}
  lr_warmup_steps: {scheduler.get('warmup_steps', 2000)}
  weight_decay: {optim['weight_decay']}
  clip_grad: {optim.get('max_grad_norm', 1.0)}
  adam_beta1: {optim.get('betas', [0.9, 0.95])[0]}
  adam_beta2: {optim.get('betas', [0.9, 0.95])[1]}

parallelism:
  dp: {launch.get('num_nodes', 1) * launch.get('gpus_per_node', 8) // max(1, launch.get('tp_degree', 1))}
  tp: {launch.get('tp_degree', 1)}
  pp: 1

tokens:
  batch_accumulation_per_replica: 1
  micro_batch_size: 4
  sequence_length: {model.get('max_sequence_length', 4096)}
  train_steps: {trainer['max_steps']}
"""

    def _generate_llm_foundry(self, config: GeneratedConfig) -> str:
        model = config.model_config
        optim = config.optimizer_config
        scheduler = config.scheduler_config
        trainer = config.trainer_config

        return f"""# LLM Foundry training config (YAML format)
# Generated by AutoPilot for: {config.name}

run_name: {config.name}
max_duration: {trainer['max_steps']}ba
save_interval: {trainer.get('checkpoint_interval', 1000)}ba
save_folder: checkpoints/{config.name}

model:
  name: mpt_causal_lm
  d_model: {model['hidden_size']}
  n_heads: {model['num_heads']}
  n_layers: {model['num_layers']}
  expansion_ratio: {model.get('intermediate_size', model['hidden_size'] * 4) / model['hidden_size']}
  max_seq_len: {model.get('max_sequence_length', 4096)}
  vocab_size: {model.get('vocab_size', 50304)}
  attn_config:
    attn_impl: flash

optimizer:
  name: decoupled_adamw
  lr: {optim['lr']}
  betas: {optim.get('betas', [0.9, 0.95])}
  weight_decay: {optim['weight_decay']}

scheduler:
  name: cosine_with_warmup
  t_warmup: {scheduler.get('warmup_steps', 2000)}ba
  alpha_f: 0.1

loggers:
  wandb:
    project: autopilot
    name: {config.name}

callbacks:
  speed_monitor:
    window_size: 50
  lr_monitor: {{}}
  memory_monitor: {{}}
  runtime_estimator: {{}}

fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
"""

    def _generate_torchtitan(self, config: GeneratedConfig) -> str:
        model = config.model_config
        optim = config.optimizer_config
        trainer = config.trainer_config
        launch = config.launch_config

        return f"""# TorchTitan training config (TOML format)
# Generated by AutoPilot for: {config.name}

[job]
dump_folder = "checkpoints/{config.name}"

[profiling]
enable_profiling = false

[metrics]
enable_tensorboard = true
log_freq = {trainer.get('log_interval', 10)}

[model]
name = "llama3"
flavor = "custom"
norm_type = "rmsnorm"
tokenizer_path = "./tokenizer.model"

[model.custom]
dim = {model['hidden_size']}
n_layers = {model['num_layers']}
n_heads = {model['num_heads']}
vocab_size = {model.get('vocab_size', 50304)}
max_seq_len = {model.get('max_sequence_length', 4096)}

[optimizer]
name = "AdamW"
lr = {optim['lr']}
weight_decay = {optim['weight_decay']}

[training]
batch_size = 4
seq_len = {model.get('max_sequence_length', 4096)}
warmup_steps = {config.scheduler_config.get('warmup_steps', 2000)}
max_norm = {optim.get('max_grad_norm', 1.0)}
steps = {trainer['max_steps']}
compile = true

[parallelism]
dp_shard_degree = {launch.get('num_nodes', 1) * launch.get('gpus_per_node', 8)}
tp_degree = {launch.get('tp_degree', 1)}

[checkpoint]
interval = {trainer.get('checkpoint_interval', 1000)}
"""

    def _generate_megatron(self, config: GeneratedConfig) -> str:
        model = config.model_config
        optim = config.optimizer_config
        trainer = config.trainer_config
        launch = config.launch_config

        return f"""#!/bin/bash
# Megatron-LM training script
# Generated by AutoPilot for: {config.name}

DISTRIBUTED_ARGS="
    --nproc_per_node {launch.get('gpus_per_node', 8)} \\
    --nnodes {launch.get('num_nodes', 1)} \\
    --master_port 6000
"

GPT_ARGS="
    --num-layers {model['num_layers']} \\
    --hidden-size {model['hidden_size']} \\
    --num-attention-heads {model['num_heads']} \\
    --seq-length {model.get('max_sequence_length', 4096)} \\
    --max-position-embeddings {model.get('max_sequence_length', 4096)} \\
    --micro-batch-size 4 \\
    --global-batch-size 256 \\
    --lr {optim['lr']} \\
    --min-lr {optim['lr'] * 0.1} \\
    --train-iters {trainer['max_steps']} \\
    --lr-decay-iters {trainer['max_steps']} \\
    --lr-decay-style cosine \\
    --lr-warmup-iters {config.scheduler_config.get('warmup_steps', 2000)} \\
    --weight-decay {optim['weight_decay']} \\
    --clip-grad {optim.get('max_grad_norm', 1.0)} \\
    --adam-beta1 {optim.get('betas', [0.9, 0.95])[0]} \\
    --adam-beta2 {optim.get('betas', [0.9, 0.95])[1]} \\
    --bf16 \\
    --use-flash-attn \\
    --swiglu \\
    --normalization RMSNorm \\
    --untie-embeddings-and-output-weights \\
    --no-position-embedding \\
    --use-rotary-position-embeddings
"

OUTPUT_ARGS="
    --log-interval {trainer.get('log_interval', 10)} \\
    --save-interval {trainer.get('checkpoint_interval', 1000)} \\
    --eval-interval {trainer.get('eval_interval', 500)} \\
    --save checkpoints/{config.name} \\
    --wandb-project autopilot \\
    --wandb-exp-name {config.name}
"

torchrun $DISTRIBUTED_ARGS pretrain_gpt.py \\
    $GPT_ARGS \\
    $OUTPUT_ARGS
"""
