"""Generates runnable OLMo-core training scripts from configuration.

Produces self-contained Python scripts that use the olmo_core API to run
pre-training or fine-tuning. These scripts are then launched via torchrun
or SLURM sbatch.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from agent_evolve.backends.olmo_core.config_translator import OLMoCoreTrainingConfig


class OLMoCoreScriptGenerator:
    """Generates self-contained OLMo-core training scripts."""

    def generate(self, config: OLMoCoreTrainingConfig, output_dir: Path) -> Path:
        """Generate a training script and write it to output_dir.

        Returns the path to the generated script.
        """
        script = self._render_script(config)
        output_dir.mkdir(parents=True, exist_ok=True)
        script_path = output_dir / "train_olmo_core.py"
        script_path.write_text(script)
        return script_path

    def _render_script(self, config: OLMoCoreTrainingConfig) -> str:
        """Render the training script as a string."""
        imports = self._render_imports(config)
        model_block = self._render_model_config(config)
        optim_block = self._render_optimizer_config(config)
        data_block = self._render_data_config(config)
        trainer_block = self._render_trainer_config(config)
        main_block = self._render_main(config)

        return f'''{imports}

{model_block}

{optim_block}

{data_block}

{trainer_block}

{main_block}
'''

    def _render_imports(self, config: OLMoCoreTrainingConfig) -> str:
        return textwrap.dedent('''\
            """OLMo-core training script generated by A-EVOLVE."""

            import sys
            from pathlib import Path

            # Add olmo-core to path if running from the integrated repo
            _olmo_core_src = Path(__file__).resolve().parents[4] / "olmo-core" / "src"
            if _olmo_core_src.exists():
                sys.path.insert(0, str(_olmo_core_src))

            from olmo_core.nn.transformer import TransformerConfig
            from olmo_core.train import TrainerConfig, prepare_training_environment, teardown_training_environment
            from olmo_core.train.train_module import TransformerTrainModuleConfig
            from olmo_core.train.train_module.transformer import (
                TransformerDataParallelConfig,
            )
            from olmo_core.train.callbacks import (
                CheckpointerCallback,
                ConsoleLoggerCallback,
                SpeedMonitorCallback,
                GarbageCollectorCallback,
                MetricSaverCallback,
            )
            from olmo_core.optim import AdamWConfig, CosWithWarmup
            from olmo_core.train.common import Duration
        ''')

    def _render_model_config(self, config: OLMoCoreTrainingConfig) -> str:
        return textwrap.dedent(f'''\
            def build_model_config() -> TransformerConfig:
                return TransformerConfig(
                    d_model={config.d_model},
                    n_layers={config.n_layers},
                    n_heads={config.n_heads},
                    vocab_size={config.vocab_size},
                    max_sequence_length={config.max_sequence_length},
                )
        ''')

    def _render_optimizer_config(self, config: OLMoCoreTrainingConfig) -> str:
        return textwrap.dedent(f'''\
            def build_train_module_config(model_config: TransformerConfig) -> TransformerTrainModuleConfig:
                return TransformerTrainModuleConfig(
                    rank_microbatch_size={config.rank_microbatch_size},
                    max_sequence_length={config.max_sequence_length},
                    optim=AdamWConfig(
                        lr={config.lr},
                        weight_decay={config.weight_decay},
                        betas={config.betas},
                    ),
                    scheduler=CosWithWarmup(
                        warmup_steps={config.warmup_steps},
                    ),
                    max_grad_norm={config.max_grad_norm},
                    dp_config=TransformerDataParallelConfig(),
                )
        ''')

    def _render_data_config(self, config: OLMoCoreTrainingConfig) -> str:
        data_paths_str = repr(config.data_paths) if config.data_paths else '[]'
        return textwrap.dedent(f'''\
            def build_data_loader(train_module):
                """Build data loader from configured paths."""
                data_paths = {data_paths_str}

                if not data_paths:
                    # Fallback: create a synthetic data source for testing
                    import torch
                    from torch.utils.data import DataLoader, TensorDataset

                    dummy_tokens = torch.randint(0, {config.vocab_size}, (1000, {config.max_sequence_length}))
                    dataset = TensorDataset(dummy_tokens)
                    return DataLoader(dataset, batch_size=4, shuffle=True)

                from olmo_core.data import NumpyFSLDatasetConfig, NumpyDataLoaderConfig

                dataset_config = NumpyFSLDatasetConfig(
                    paths=data_paths,
                    sequence_length={config.max_sequence_length},
                )
                loader_config = NumpyDataLoaderConfig(
                    global_batch_size={config.global_batch_size} * {config.max_sequence_length},
                    seed=42,
                )
                dataset = dataset_config.build()
                return loader_config.build(
                    dataset,
                    dp_process_group=train_module.dp_process_group,
                )
        ''')

    def _render_trainer_config(self, config: OLMoCoreTrainingConfig) -> str:
        wandb_callback = ''
        if config.wandb_project:
            wandb_callback = f'''
                .with_callback(
                    "wandb",
                    WandBCallback(project="{config.wandb_project}", name="{config.wandb_run_name or "a-evolve-run"}"),
                )'''

        metric_callback = ''
        if config.metric_report_url:
            metric_callback = f'''
                .with_callback(
                    "metric_reporter",
                    MetricSaverCallback(save_dir="{config.save_folder}/metrics"),
                )'''

        return textwrap.dedent(f'''\
            def build_trainer_config() -> TrainerConfig:
                return (
                    TrainerConfig(
                        save_folder="{config.save_folder}",
                        max_duration=Duration.steps({config.max_steps}),
                        metrics_collect_interval={config.log_interval},
                    )
                    .with_callback("checkpointer", CheckpointerCallback(save_interval={config.save_interval}))
                    .with_callback("console_logger", ConsoleLoggerCallback())
                    .with_callback("speed_monitor", SpeedMonitorCallback())
                    .with_callback("gc", GarbageCollectorCallback()){wandb_callback}{metric_callback}
                )
        ''')

    def _render_main(self, config: OLMoCoreTrainingConfig) -> str:
        load_block = ''
        if config.load_path:
            load_block = f'''
    # Resume from checkpoint
    trainer_config.load_path = "{config.load_path}"'''

        return textwrap.dedent(f'''\
            def main():
                prepare_training_environment(seed=42)

                model_config = build_model_config()
                train_module_config = build_train_module_config(model_config)
                trainer_config = build_trainer_config(){load_block}

                # Build model
                model = model_config.build(init_device="meta")

                # Build train module
                train_module = train_module_config.build(model)

                # Build data loader
                data_loader = build_data_loader(train_module)

                # Build trainer and run
                trainer = trainer_config.build(train_module, data_loader)
                trainer.fit()

                teardown_training_environment()


            if __name__ == "__main__":
                main()
        ''')
