"""Generates runnable OLMo-core training scripts from configuration.

Produces self-contained Python scripts that use the olmo_core API to run
pre-training or fine-tuning. These scripts are then launched via torchrun
or SLURM sbatch.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from agent_evolve.backends.olmo_core.config_translator import OLMoCoreTrainingConfig


class OLMoCoreScriptGenerator:
    """Generates self-contained OLMo-core training scripts."""

    def __init__(self, olmo_core_path: Path | None = None) -> None:
        if olmo_core_path:
            self._olmo_core_path = olmo_core_path
        else:
            self._olmo_core_path = Path(__file__).resolve().parents[3] / "olmo-core"

    def generate(self, config: OLMoCoreTrainingConfig, output_dir: Path) -> Path:
        """Generate a training script and write it to output_dir.

        Returns the path to the generated script.
        """
        script = self._render_script(config)
        output_dir.mkdir(parents=True, exist_ok=True)
        script_path = output_dir / "train_olmo_core.py"
        script_path.write_text(script)
        return script_path

    def _render_script(self, config: OLMoCoreTrainingConfig) -> str:
        imports = self._render_imports()
        model_block = self._render_model_config(config)
        train_module_block = self._render_train_module_config(config)
        data_block = self._render_data_config(config)
        trainer_block = self._render_trainer_config(config)
        main_block = self._render_main(config)

        return f'''{imports}

{model_block}

{train_module_block}

{data_block}

{trainer_block}

{main_block}
'''

    def _render_imports(self) -> str:
        olmo_core_src = str(self._olmo_core_path / "src")
        return textwrap.dedent(f'''\
            """OLMo-core training script generated by A-EVOLVE."""

            import sys
            from pathlib import Path

            _olmo_core_src = Path("{olmo_core_src}")
            if _olmo_core_src.exists():
                sys.path.insert(0, str(_olmo_core_src))

            from olmo_core.data import NumpyDataLoaderConfig, NumpyFSLDatasetConfig, TokenizerConfig
            from olmo_core.nn.transformer import TransformerConfig
            from olmo_core.optim import AdamWConfig, CosWithWarmup
            from olmo_core.train import Duration, TrainerConfig, prepare_training_environment, teardown_training_environment
            from olmo_core.train.callbacks import (
                CheckpointerCallback,
                ConsoleLoggerCallback,
                GarbageCollectorCallback,
                MetricSaverCallback,
                SpeedMonitorCallback,
                WandBCallback,
            )
            from olmo_core.train.train_module import TransformerTrainModuleConfig
            from olmo_core.train.train_module.transformer import TransformerDataParallelConfig
        ''')

    def _render_model_config(self, config: OLMoCoreTrainingConfig) -> str:
        factory = config.model_factory or self._select_factory_method(config)
        return textwrap.dedent(f'''\
            TOKENIZER = TokenizerConfig.dolma2()


            def build_model_config() -> TransformerConfig:
                return TransformerConfig.{factory}(vocab_size=TOKENIZER.padded_vocab_size())
        ''')

    def _select_factory_method(self, config: OLMoCoreTrainingConfig) -> str:
        """Pick the closest OLMo2 factory method based on d_model size."""
        size_to_factory = [
            (768, "olmo2_190M"),
            (1024, "olmo2_370M"),
            (1536, "olmo2_760M"),
            (2048, "olmo2_1B"),
            (3328, "olmo2_3B"),
            (4096, "olmo2_7B"),
            (5120, "olmo2_13B"),
            (5632, "olmo2_32B"),
        ]
        for d_model, factory in size_to_factory:
            if config.d_model <= d_model:
                return factory
        return "olmo2_32B"

    def _render_train_module_config(self, config: OLMoCoreTrainingConfig) -> str:
        return textwrap.dedent(f'''\
            def build_train_module_config() -> TransformerTrainModuleConfig:
                return TransformerTrainModuleConfig(
                    rank_microbatch_size={config.rank_microbatch_size},
                    max_sequence_length={config.max_sequence_length},
                    optim=AdamWConfig(
                        lr={config.lr},
                        weight_decay={config.weight_decay},
                        betas={config.betas},
                    ),
                    scheduler=CosWithWarmup(warmup={config.warmup_steps}),
                    max_grad_norm={config.max_grad_norm},
                    dp_config=TransformerDataParallelConfig(),
                )
        ''')

    def _render_data_config(self, config: OLMoCoreTrainingConfig) -> str:
        data_paths_str = repr(config.data_paths) if config.data_paths else '[]'
        return textwrap.dedent(f'''\
            def build_data_loader(train_module):
                """Build data loader from configured paths."""
                data_paths = {data_paths_str}

                existing_paths = [p for p in data_paths if Path(p).exists()]
                if not existing_paths:
                    raise RuntimeError(
                        f"No data paths found. Expected: {{data_paths}}. "
                        f"Please run data preparation first."
                    )

                dataset_config = NumpyFSLDatasetConfig(
                    paths=existing_paths,
                    sequence_length={config.max_sequence_length},
                    tokenizer=TOKENIZER,
                )
                loader_config = NumpyDataLoaderConfig(
                    global_batch_size={config.global_batch_size * config.max_sequence_length},
                    seed=42,
                )
                dataset = dataset_config.build()
                return loader_config.build(dataset, dp_process_group=train_module.dp_process_group)
        ''')

    def _render_trainer_config(self, config: OLMoCoreTrainingConfig) -> str:
        wandb_callback = ''
        if config.wandb_project:
            wandb_callback = f'''
        .with_callback(
            "wandb",
            WandBCallback(project="{config.wandb_project}", name="{config.wandb_run_name or "a-evolve-run"}"),
        )'''

        metric_callback = ''
        if config.metric_report_url:
            metric_callback = f'''
        .with_callback("metric_saver", MetricSaverCallback())'''

        return textwrap.dedent(f'''\
            def build_trainer_config() -> TrainerConfig:
                return (
                    TrainerConfig(
                        save_folder="{config.save_folder}",
                        max_duration=Duration.steps({config.max_steps}),
                        metrics_collect_interval={config.log_interval},
                    )
                    .with_callback("checkpointer", CheckpointerCallback(save_interval={config.save_interval}))
                    .with_callback("console_logger", ConsoleLoggerCallback())
                    .with_callback("speed_monitor", SpeedMonitorCallback())
                    .with_callback("gc", GarbageCollectorCallback()){wandb_callback}{metric_callback}
                )
        ''')

    def _render_main(self, config: OLMoCoreTrainingConfig) -> str:
        load_block = ''
        if config.load_path:
            load_block = f'''
                trainer_config.load_path = "{config.load_path}"'''

        return textwrap.dedent(f'''\
            def main():
                prepare_training_environment(seed=42)

                model_config = build_model_config()
                model = model_config.build(init_device="meta")

                train_module_config = build_train_module_config()
                train_module = train_module_config.build(model)

                data_loader = build_data_loader(train_module){load_block}

                trainer_config = build_trainer_config()
                trainer = trainer_config.build(train_module, data_loader)
                trainer.fit()

                teardown_training_environment()


            if __name__ == "__main__":
                main()
        ''')
